In [17]:
from netCDF4 import Dataset,MFDataset

In [4]:
nc=Dataset('fwproject\\TS_fire_online_01_2017.08_NA2.nc','r')

In [18]:
TS_fire=MFDataset('fwproject\\TS_fire_online_*nc','r')
TS_nofire=MFDataset('fwproject\\TS_nofire_online_*nc','r')

In [5]:
for i in nc.variables:
    #print(i)
    print(i)

TS
lat
lon
time
time_bnds


In [20]:
for i in TS_fire.variables:
    #print(i)
    print(i)

TS
lat
lon
time
time_bnds


In [6]:
nc.variables,nc.variables['lat']

(OrderedDict([('TS', <class 'netCDF4._netCDF4.Variable'>
               float32 TS(time, lat, lon)
                   long_name: Surface temperature (radiative)
                   units: K
                   cell_methods: time: mean
               unlimited dimensions: time
               current shape = (1, 53, 89)
               filling on, default _FillValue of 9.969209968386869e+36 used),
              ('lat', <class 'netCDF4._netCDF4.Variable'>
               float64 lat(lat)
                   standard_name: latitude
                   long_name: latitude
                   units: degrees_north
                   axis: Y
               unlimited dimensions: 
               current shape = (53,)
               filling on, default _FillValue of 9.969209968386869e+36 used),
              ('lon', <class 'netCDF4._netCDF4.Variable'>
               float64 lon(lon)
                   standard_name: longitude
                   long_name: longitude
                   units: degrees_east

In [29]:
nc.dimensions

OrderedDict([('time',
              <class 'netCDF4._netCDF4.Dimension'> (unlimited): name = 'time', size = 1),
             ('lat',
              <class 'netCDF4._netCDF4.Dimension'>: name = 'lat', size = 53),
             ('lon',
              <class 'netCDF4._netCDF4.Dimension'>: name = 'lon', size = 89),
             ('bnds',
              <class 'netCDF4._netCDF4.Dimension'>: name = 'bnds', size = 2)])

In [31]:
nc.variables['time_bnds'].dimensions

('time', 'bnds')

for nf in range(10):
 f = Dataset("mftest%s.nc" % nf,"w")
    f.createDimension("x",None)
    x = f.createVariable("x","i",("x",))
     x[0:10] = numpy.arange(nf*10,10*(nf+1))
     f.close()

In [33]:
print(nc)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_64BIT data model, file format NETCDF3):
    CDI: Climate Data Interface version 1.7.2 (http://mpimet.mpg.de/cdi)
    Conventions: CF-1.0
    history: Fri Dec 21 09:30:55 2018: ncks -O -d lon,200.,310. -d lat,20.,70. /glade/work/dianab/new_proc/online//fire_online_01/TS_fire_online_01_2017.08.nc TS_fire_online_01_2017.08_NA2.nc
Fri Sep 14 12:18:04 2018: cdo select,name=TS /glade/scratch_old/dianab/f.e20.FSDC.f09_f09_2017_FIRE_online_01_180803/run/f.e20.FSDC.f09_f09_2017_FIRE_online_01_180803.cam.h0.2017-08.nc TS_fire_online_01_2017.08.nc
    source: CAM
    case: f.e20.FSDC.f09_f09_2017_FIRE_online_01_180803
    title: UNSET
    logname: dianab
    host: cheyenne4
    Version: $Name$
    revision_Id: $Id$
    initial_file: f.e20.FSDC.f09_f09_2011-2017_FIREx3.5_vert_180708.cam.i.2017-04-01-21600.nc
    topography_file: /glade/p/cesmdata/cseg/inputdata/atm/cam/topo/fv_0.9x1.25_nc3000_Nsw042_Nrs008_Co060_Fi001_ZR_geos5_c160702.nc
    t

In [82]:
lons = nc.variables['lon'][:]
lats = nc.variables['lat'][:]
ts = nc.variables['TS'][:]

ts_units = nc.variables['TS'].units

In [83]:
lons.shape,lats.shape,ts.shape

((89,), (53,), (1, 53, 89))

In [21]:
lons_fire = TS_fire.variables['lon'][:]
lats_fire = TS_fire.variables['lat'][:]
ts_fire = TS_fire.variables['TS'][:]

ts_units_fire = TS_fire.variables['TS'].units

In [22]:
lons_fire.shape,lats_fire.shape,ts_fire.shape

((89,), (53,), (21, 53, 89))

In [10]:
len(lons),len(lats),len(ts)
nc.variables.keys()
nc.variables['TS']

<class 'netCDF4._netCDF4.Variable'>
float32 TS(time, lat, lon)
    long_name: Surface temperature (radiative)
    units: K
    cell_methods: time: mean
unlimited dimensions: time
current shape = (1, 53, 89)
filling on, default _FillValue of 9.969209968386869e+36 used

In [32]:
print(lons,lats,ts)
print(lons.shape,lats.shape,ts.shape)

[200.   201.25 202.5  203.75 205.   206.25 207.5  208.75 210.   211.25
 212.5  213.75 215.   216.25 217.5  218.75 220.   221.25 222.5  223.75
 225.   226.25 227.5  228.75 230.   231.25 232.5  233.75 235.   236.25
 237.5  238.75 240.   241.25 242.5  243.75 245.   246.25 247.5  248.75
 250.   251.25 252.5  253.75 255.   256.25 257.5  258.75 260.   261.25
 262.5  263.75 265.   266.25 267.5  268.75 270.   271.25 272.5  273.75
 275.   276.25 277.5  278.75 280.   281.25 282.5  283.75 285.   286.25
 287.5  288.75 290.   291.25 292.5  293.75 295.   296.25 297.5  298.75
 300.   301.25 302.5  303.75 305.   306.25 307.5  308.75 310.  ] [20.2617801  21.20418848 22.14659686 23.08900524 24.03141361 24.97382199
 25.91623037 26.85863874 27.80104712 28.7434555  29.68586387 30.62827225
 31.57068063 32.51308901 33.45549738 34.39790576 35.34031414 36.28272251
 37.22513089 38.16753927 39.10994764 40.05235602 40.9947644  41.93717277
 42.87958115 43.82198953 44.76439791 45.70680628 46.64921466 47.59162304
 4

In [12]:
TS_list=nc.variables['TS']
Ts_list=TS_list[:]
print(Ts_list)
print(Ts_list.shape)

[[[300.86063 300.76196 300.6574  ... 301.22238 301.14532 301.12277]
  [300.5201  300.41257 300.34134 ... 301.14435 301.0628  301.0515 ]
  [300.14337 300.0224  299.99057 ... 301.11432 301.01407 300.99176]
  ...
  [282.93866 283.6101  283.4969  ... 280.4468  281.51422 277.79807]
  [280.7121  281.2655  281.14685 ... 281.98694 281.65613 274.59637]
  [279.95972 280.12302 280.5091  ... 278.58594 282.61847 276.9667 ]]]
(1, 53, 89)


In [13]:
lon_0 = lons.mean()
lat_0 = lats.mean()

In [84]:
import numpy as np
lons_fire = TS_fire.variables['lon'][:]
lats_fire = TS_fire.variables['lat'][:]
ts_fire = TS_fire.variables['TS'][:]

ts_units_fire = TS_fire.variables['TS'].units

In [85]:
ts_fire.shape
sample2_np=np.zeros((1,53, 89))
for i in range(ts_fire.shape[0]):
    sample_np=np.array(ts_fire[i])
    sample1_np=sample_np.reshape((1,53, 89))
    sample2_np=sample2_np+sample1_np
    
sample3_np=sample2_np/ts_fire.shape[0]


(53, 89)

In [33]:
lons_fire_0 = lons_fire.mean()
lats_fire_0 = lats_fire.mean()
ts_fire_0 = ts_fire.mean()

In [34]:
lons_fire_0,lats_fire_0,ts_fire_0

(255.0, 44.764397905759154, 292.79578)

In [23]:
"""
print("Hello")
from netCDF4 import Dataset
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap
import numpy as np

nc=Dataset('D:\\Data Science\\DeepLearning\\Time Series\\fwproject\\TS_fire_online_01_2017.08_NA2.nc','r')
for i in nc.variables:
    #print(i)
    print(i)

lons = nc.variables['lon'][:]
lats = nc.variables['lat'][:]
ts = nc.variables['TS'][:]

ts_units = nc.variables['TS'].units

lon_0 = lons.mean()
lat_0 = lats.mean()
print("hello3")
m = Basemap(width=5000000,height=3500000,
            resolution='l',projection='stere',\
            lat_ts=40,lat_0=lat_0,lon_0=lon_0)

lon, lat = np.meshgrid(lons, lats)
xi, yi = m(lon, lat)
# Plot Data
cs = m.pcolor(xi,yi,np.squeeze(ts))

# Add Grid Lines
m.drawparallels(np.arange(-80., 81., 10.), labels=[1,0,0,0], fontsize=10)
m.drawmeridians(np.arange(-180., 181., 10.), labels=[0,0,0,1], fontsize=10)

# Add Coastlines, States, and Country Boundaries
m.drawcoastlines()
m.drawstates()
m.drawcountries()

# Add Colorbar
cbar = m.colorbar(cs, location='bottom', pad="10%")
cbar.set_label(ts_units)

# Add Title
plt.title('DJF Maximum Temperature')

plt.show()"""

'\nprint("Hello")\nfrom netCDF4 import Dataset\nimport matplotlib.pyplot as plt\nfrom mpl_toolkits.basemap import Basemap\nimport numpy as np\n\nnc=Dataset(\'D:\\Data Science\\DeepLearning\\Time Series\\fwproject\\TS_fire_online_01_2017.08_NA2.nc\',\'r\')\nfor i in nc.variables:\n    #print(i)\n    print(i)\n\nlons = nc.variables[\'lon\'][:]\nlats = nc.variables[\'lat\'][:]\nts = nc.variables[\'TS\'][:]\n\nts_units = nc.variables[\'TS\'].units\n\nlon_0 = lons.mean()\nlat_0 = lats.mean()\nprint("hello3")\nm = Basemap(width=5000000,height=3500000,\n            resolution=\'l\',projection=\'stere\',            lat_ts=40,lat_0=lat_0,lon_0=lon_0)\n\nlon, lat = np.meshgrid(lons, lats)\nxi, yi = m(lon, lat)\n# Plot Data\ncs = m.pcolor(xi,yi,np.squeeze(ts))\n\n# Add Grid Lines\nm.drawparallels(np.arange(-80., 81., 10.), labels=[1,0,0,0], fontsize=10)\nm.drawmeridians(np.arange(-180., 181., 10.), labels=[0,0,0,1], fontsize=10)\n\n# Add Coastlines, States, and Country Boundaries\nm.drawcoastline